apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: angular 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: angular 
    spec:
      containers:
        - name: angular 
          image: kubernetestes.azurecr.io/angular
          ports:
          - containerPort: 8